# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d921147ea921d427c0a42bf90a1e3899255b3e0b9e76e347c3236d680016810a6baed838485f096c0e80a2abf136c3aa91f4caede4f009f0a49228189658478

test:
  secret_key_base: dc73d9bded69800be2effcf408f1bdc47f56f808df80705864e254274ebcef97d482cbcd711ac0ea99411de66d8041ee1fe01e26bfba2520459a2e790db20d53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
