# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96cf5638634585ec116c27b7eb63dfbb460edfb77fed01e902b4912c5573fb79511a8ed62a7915fc06cb27867e85997f08e76f4953ee7e2983657e369ab1bb94

test:
  secret_key_base: a3a79a8e084b18e7af05179f44b17df446f4a21c8d52a7c7cec8595e2c233ea8486eb94cac20d6f0daefe8cf9475b0e05a76a816ad462d7ab3a786b9702c26a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
